### PR TITLE
Relax `bytestring` upper bound and bump to Stackage LTS-18.28

### PR DESCRIPTION
**Pull request by dynamicboid**
This PR has just minor constraint changes in order to render it more compatible with newer Haskell projects.

### CODE REVIEW

**Comment by neilmayhew** [comment]
Any chance of a new Hackage release for this?

**Comment by leptonyu** [comment]
I'll publish `0.1.0` late today.

**Comment by dynamicboid** [comment]
Thanks so much for accepting my PR and doing a new release!

**Comment by leptonyu** [comment]
Thank you for your contribution.

**Pull request merged**
