### PR TITLE
Various packaging and performance fixes

### PR DESCRIPTION
**Pull request by dcoutts**
We start by adding a simple benchmark.

Here are the baseline results on my box, before any fixes and improvements.
```
benchmarking crc32c small
time                 419.6 ns   (416.5 ns .. 423.4 ns)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 419.1 ns   (417.2 ns .. 423.1 ns)
std dev              9.071 ns   (5.273 ns .. 16.31 ns)
variance introduced by outliers: 28% (moderately inflated)

benchmarking crc32c large
time                 59.44 μs   (59.17 μs .. 59.69 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 59.33 μs   (59.16 μs .. 59.62 μs)
std dev              746.9 ns   (564.4 ns .. 1.049 μs)
```
where "small" is 2^8 bytes and large is 2^16 bytes.

The first fix is then to compile the C++ code properly, using `cxx-sources` and `cxx-options`. This already improves the benchmarks substantially:
```
benchmarking crc32c small
time                 204.0 ns   (203.2 ns .. 205.0 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 204.3 ns   (203.6 ns .. 204.9 ns)
std dev              2.098 ns   (1.765 ns .. 2.504 ns)

benchmarking crc32c large
time                 16.99 μs   (16.94 μs .. 17.03 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 16.97 μs   (16.92 μs .. 17.02 μs)
std dev              164.7 ns   (126.0 ns .. 236.3 ns)
```
Note that this fix should also fix building on OSX, by passing `-std=c++11`.

Next is to use the specialised amd64 SSE4.2 and arm implementations on the supported platforms, rather than the generic version, by using the correct CPP defines (without the __ prefixes). This also improves the benchmarks substantially.
```
benchmarking crc32c small
time                 129.5 ns   (129.1 ns .. 130.0 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 130.3 ns   (129.9 ns .. 130.7 ns)
std dev              1.417 ns   (1.050 ns .. 1.894 ns)

benchmarking crc32c large
time                 2.607 μs   (2.602 μs .. 2.611 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.603 μs   (2.597 μs .. 2.617 μs)
std dev              31.05 ns   (16.13 ns .. 66.94 ns)
```

### CODE REVIEW

**Comment by dcoutts** [comment]
This is a WIP intended to address #3.

**Comment by dcoutts** [comment]
Final version, after using `unsafe` FFI calls is around 15x faster for the small case (2^8 bytes) and around 25x faster for the large case (2^16 bytes).
```
benchmarking crc32c small
time                 26.76 ns   (26.57 ns .. 26.98 ns)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 26.79 ns   (26.65 ns .. 26.95 ns)
std dev              486.5 ps   (405.3 ps .. 631.3 ps)
variance introduced by outliers: 25% (moderately inflated)

benchmarking crc32c large
time                 2.345 μs   (2.332 μs .. 2.357 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.345 μs   (2.335 μs .. 2.356 μs)
std dev              36.49 ns   (29.70 ns .. 49.10 ns)
variance introduced by outliers: 15% (moderately inflated)
```

**Comment by dcoutts** [comment]
This should now also build out of the box on Windows and OSX, fixing #3.

**Comment by dcoutts** [comment]
Note this is split into lots of little patches with the intention of making review easier. If you prefer it all squashed together, let me know.

**Comment by dcoutts** [comment]
At the suggestion of @phadej, use safe or unsafe FFI below/above a size threshold to avoid long running calls blocking other threads or GC.

I picked the threshold to be 16k, and I've extended the benchmark so you can see the effect: 16k+1 takes about 8% longer than 16k.
```
benchmarking crc32c small (2^8)
time                 25.24 ns   (25.18 ns .. 25.29 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 25.21 ns   (25.13 ns .. 25.29 ns)
std dev              274.3 ps   (210.2 ps .. 365.5 ps)
variance introduced by outliers: 11% (moderately inflated)

benchmarking crc32c large (2^16)
time                 2.284 μs   (2.276 μs .. 2.293 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.283 μs   (2.277 μs .. 2.288 μs)
std dev              18.42 ns   (13.74 ns .. 24.63 ns)

benchmarking crc32c large (2^16+1)
time                 2.469 μs   (2.458 μs .. 2.481 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.471 μs   (2.463 μs .. 2.478 μs)
std dev              26.60 ns   (20.54 ns .. 36.22 ns)
```

**Comment by leptonyu** [comment]
Thank you for the contribution.
 I will review later.

**Pull request merged**
